### ISSUE TITLE
Thank you very much & Setup

### ISSUE THREAD

**Issue by stevenhardy-digital** [diadal/universal-social-auth#1]
Hello @diadal 

I just want to say thank you very much for getting this new version of vue-social-auth live. 

Unfortunately being a Typescript novice, I am completely unsure how to set this up now within my Vue 2 SPA. Your README.md is good, but unfortunately, I am unable to follow it to be able to use this package within my application. 

Do you have any guides or example projects that I can take a look at please?

**Comment by diadal** [comment]
can you share with Codepen to i can see how to config

**Comment by diadal** [comment]
you don't need to use typescript declaration if your app don't use that just import normal and use

**Comment by stevenhardy-digital** [comment]
Hello @diadal 

I have created a code pen to show you my set up. If you need access to the repo, then thats fine as well. [CodePen](https://codepen.io/stevenhardy-digital/pen/gOLJyEd)

**Comment by diadal** [comment]
https://diadal.github.io/universal-social-auth-test-vu2/ working check the example
