### ISSUE TITLE
Prompt mobile app instead of browser

### ISSUE THREAD

**Issue by jordib123** [diadal/universal-social-auth#12]
Firstly, thank you for this great package.

I have one question: When trying to use the social login on mobile (for example Facebook) it will prompt the Facebook login screen in the browser instead of the Facebook app. Because I am not logged in to Facebook in the browser, but only in the actual mobile app, I still need to fill in my username and password. Is there a way to prompt the Facebook app instead of the browser login screen so it will automatically sign me in using the app?

**Comment by diadal** [comment]
you can't do that your app wont be able to access Facebook app data

**Comment by jordib123** [comment]
@diadal Ok, so it is just not possible at all? Whatever package/implementation I would use?
