### ISSUE TITLE
Reference Error self is not defined

### ISSUE THREAD

**Issue by ibraahim6** [diadal/universal-social-auth#13]
Hello,
i use your package in nuxt app with version vue2
and this error will showning with me 
please any solation?? 
![image](https://user-images.githubusercontent.com/37673631/194730487-9f0f03e4-aec5-4435-b5c5-4d88b9f08371.png)

**Comment by ibraahim6** [comment]
this my file plugin to use your package...
`
// import Vue from 'vue'
import axios from 'axios'
import UniversalSocialauth from 'universal-social-auth'

// Vue.config.productionTip = false

const options = {
    providers: {
        // apple: {
        //   nonce: '**************',
        //   state: '**************',
        //   clientId: '**************',
        //   redirectUri: 'https://myapp.com/auth/github/callback'
        // },
        // github: {
        //     clientId: '78bfc07e1f25b5e22c26',
        //     redirectUri: 'https://diadal.com.ng/auth/github/callback'
        // },
        // twitch: {
        //     clientId: 'qi4vbk30uuvuqigcd5ioq3egxf67m8',
        //     redirectUri: 'https://diadal.com.ng/auth/twitch/callback'
        // },
        google: {
            clientId: '172143351810-strhg4to27p0t4gaiqb7bdph1e841gbo.apps.googleusercontent.com',
            redirectUri: 'http://localhost:3000/auth/google/callback'
        },
        // facebook: {
        //   clientId: '************',
        //   redirectUri: 'https://myapp.com/auth/facebook/callback'
        // },
        // twitter: {
        //   url: 'https://myapp.com/auth/twitter',
        //   clientId: '********',
        //   redirectUri: 'https://myapp.com/auth/twitter/callback'
        // }
    }
}

const Oauth = new UniversalSocialauth(axios, options)

// Vue.prototype.$axios = axios
// Vue.prototype.$Oauth = Oauth

export default Oauth;`

**Comment by ibraahim6** [comment]
this my file plugin to use your package...

`// import Vue from 'vue'
import axios from 'axios'
import UniversalSocialauth from 'universal-social-auth'

// Vue.config.productionTip = false

const options = {
providers: {
// apple: {
// nonce: '',
// state: '',
// clientId: '',
// redirectUri: 'https://myapp.com/auth/github/callback'
// },
// github: {
// clientId: '',
// redirectUri: 'https://diadal.com.ng/auth/github/callback'
// },
// twitch: {
// clientId: ',
// redirectUri: 'https://diadal.com.ng/auth/twitch/callback'
// },
google: {
clientId: '',
redirectUri: 'http://localhost:3000/auth/google/callback'
},
// facebook: {
// clientId: '',
// redirectUri: 'https://myapp.com/auth/facebook/callback'
// },
// twitter: {
// url: 'https://myapp.com/auth/twitter',
// clientId: '********',
// redirectUri: 'https://myapp.com/auth/twitter/callback'
// }
}
}

const Oauth = new UniversalSocialauth(axios, options)

// Vue.prototype.$axios = axios
// Vue.prototype.$Oauth = Oauth

export default Oauth;`

**Comment by diadal** [comment]
check this tut https://github.com/diadal/universal-social-auth-test-nuxt

**Comment by ibraahim6** [comment]
i check it by my self and the issue still exists

**Comment by ibraahim6** [comment]
and i use nuxt with javascript .. i checked this your repo => https://github.com/diadal/universal-social-auth-test-nuxt-js

**Comment by jawainc** [comment]
@ZajdeR having same problem on nuxt 2
can you explain **passing providerData as object** by example

**Comment by diadal** [comment]
> @ZajdeR having same problem on nuxt 2 can you explain **passing providerData as object** by example

you do not need to import the providerData simply create the data object and use
