### ISSUE TITLE
Plugin fails in NustJs

### ISSUE THREAD

**Issue by bekee** [diadal/universal-social-auth#3]
**Describe the bug**
I get this error self is not defined when I import the the provider in a component 

Kindly review why or give a guide on how to use in NuxtJs

**Comment by diadal** [comment]
can you share your code with https://codepen.io

**Comment by diadal** [comment]
`import { Providers } from 'universal-social-auth'`
`import { ProderT } from 'universal-social-auth/dist/providers'`
should without any issue

**Comment by bekee** [comment]
I added a plugin socialauth.js

import Vue from 'vue'
import axios from 'axios'
import UniversalSocialauth from 'universal-social-auth'

const options = {
    providers: {  
      google: {
        clientId:  process.env.GOOGLE_ID,
        redirectUri: process.env.API_HOST + '/auth/google/callback'
      },
      facebook: {
        clientId:  process.env.FACEBOOK_ID,
        redirectUri: process.env.API_HOST + '/auth/facebook/callback'
      },
      
    }
  }

  const Oauth = new UniversalSocialauth(axios, options)

 
Vue.prototype.$Oauth = Oauth



the imported the plugin to nuxt.config.js

{ src: '~/plugins/mixins/socialauth', ssr: false },


then I imported the provider in a component


// import { Providers} from 'universal-social-auth'
// Button M2
import { Facebook, Google} from 'universal-social-auth'
OR
import { Facebook, Google, /*Github , Twitter*/} from 'universal-social-auth/dist/providers'

any the imports in component generates the error "self is not defined"


I'm using 
"universal-social-auth": "^0.1.9",
"nuxt": "^2.14.0",

**Comment by diadal** [comment]
it work great nuxt check https://github.com/diadal/universal-social-auth-test-nuxt 

<img width="995" alt="Screen Shot 2021-04-02 at 11 50 55 AM" src="https://user-images.githubusercontent.com/19895516/113409695-bf1c6f80-93a9-11eb-8118-aec8cbedc12d.png">
<img width="469" alt="Screen Shot 2021-04-02 at 12 00 07 PM" src="https://user-images.githubusercontent.com/19895516/113410285-fc353180-93aa-11eb-803b-31c3a2bc6b43.png">

**Comment by bekee** [comment]
https://github.com/diadal/universal-social-auth-test-nuxt
The link is invalid,  can you resend

**Comment by diadal** [comment]
have make it public it should work now `https://github.com/diadal/universal-social-auth-test-nuxt`

**Comment by diadal** [comment]
am sure is a little typo in your project just check the test project it should worked

**Comment by diadal** [comment]
i guess you get it worked by now

**Comment by diadal** [comment]
you can reopen the issue if not

**Comment by bekee** [comment]
Unfortunately I couldn't, this plugin is on typescript whereas my project is on JavaScript  and keeps returning same error, I had pop for vue-social-auth

**Comment by diadal** [comment]
just remove all the typescript code line it work without issue

**Comment by diadal** [comment]
https://github.com/diadal/universal-social-auth-test-nuxt-js pure nuxtjs javascript 

<img width="395" alt="Screen Shot 2021-04-05 at 3 26 43 PM" src="https://user-images.githubusercontent.com/19895516/113587479-be444180-9626-11eb-9092-a7e2f9adac3a.png">
<img width="1006" alt="Screen Shot 2021-04-05 at 3 27 03 PM" src="https://user-images.githubusercontent.com/19895516/113587497-c3a18c00-9626-11eb-8dc9-f45a45ffc5c0.png">

**Comment by ShadXst** [comment]
Faced the same issue on ver. 0.2.5.

```
ReferenceError
self is not defined
in node_modules/universal-social-auth/dist/index.js
@1:282
```

**Comment by diadal** [comment]
check this out download and run https://github.com/diadal/universal-social-auth-test-nuxt-js then check with your code

**Comment by ShadXst** [comment]
Yes, it works. But I can't understand exactly where the problem is coming from, because I pasted my solution for front-end(client) from this link. :)

**Comment by diadal** [comment]
> Yes, it works. But I can't understand exactly where the problem is coming from, because I pasted my solution for front-end(client) from this link. :)

can you share your code

**Comment by san4io** [comment]
I use nuxt2 with composition api, have same issue, I've created plugin with mode: client

My plugin file:
```
import axios from 'axios'
import UniversalSocialauth from 'universal-social-auth'
import { defineNuxtPlugin } from '@nuxtjs/composition-api'
import '@nuxt/types'

declare module '@nuxt/types' {
    interface Context {
        $social: UniversalSocialauth;
    }
}

const options = {
    providers: {
        google: {
          clientId: '****',
          redirectUri: 'http://localhost:3000/social/google'
        },
        facebook: {
          clientId: '****',
          redirectUri: 'http://localhost:3000/social/facebook'
        },
    },
}


export default defineNuxtPlugin(ctx => {
    ctx.$social = new UniversalSocialauth(axios, options)
})
```
While navigating from client - OK.
If I'm making direct refresh on that page(SSR). I receive:

![image](https://user-images.githubusercontent.com/12079341/140626841-c9e362ba-2e59-4ab1-aa70-a0fc33e430f4.png)

**Comment by san4io** [comment]
Any news?

**Comment by ZajdeR** [comment]
The issue on SSR mode is only when passing providerData. You can add it as object. I use the same that are in repo, then problem is solved.
